services:
  db:
    image: postgres:16
    container_name: sgrn_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sgrn_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: sgrn
        uid: 1000
    container_name: sgrn_app
    restart: unless-stopped
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    environment:
      - DB_HOST=db
    networks:
      - sgrn_network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile

    container_name: sgrn_nginx
    restart: unless-stopped
    ports:
      - "8401:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - sgrn_network

networks:
  sgrn_network:
    driver: bridge

volumes:
  postgres_data:
